---
- name: Add node package key.
  apt_key:
    url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    id=68576280
    state=present

- name: Add node repo.
  apt_repository: >
    repo='deb https://deb.nodesource.com/node_5.x trusty main'

- name: Install node
  apt:
    pkg={{ item }}
    state=installed
    install_recommends=no
    cache_valid_time=1800
    update_cache=yes
  with_items:
  - nodejs

- name: Link nodejs to node
  file:
    src=/usr/bin/nodejs
    dest=/usr/bin/node
    state=link
